send_message:
  name: 发送 HarmonyOS 通知
  description: 向选定的 HarmonyOS 设备发送通知。
  fields:
    entity_id:
      name: 通知实体
      description: 选择要接收通知的 HarmonyOS 设备。
      required: true
      selector:
        entity:
          multiple: true
          filter:
            domain: notify
    title:
      name: 标题
      description: 通知标题。
      required: false
      selector:
        text: {}
    message:
      name: 正文
      description: 通知正文。
      required: true
      selector:
        text: {}
    data:
      name: 自定义数据
      description: 随通知发送的可选自定义数据。
      required: false
      selector:
        object: {}
    persistent:
      name: App 落库
      description: 将通知写入 App 通知历史。
      required: false
      default: false
      selector:
        boolean: {}
